spring.data.mongodb.uri=mongodb+srv://DiyaPatel:DiyaOAtel@cluster0.zhz2yic.mongodb.net/?appName=Cluster0
spring.data.mongodb.database=journaldb
spring.data.mongodb.auto-index-creation=true
server.port =  8080
server.servlet.context-path= /journal


#spring.data.mongodb.username=myjournaluser
#spring.data.mongodb.password=mypassword
